on:
  push:
    branches: [ develop, bugfix/*, feature/*, release/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build-validation:
    uses: abbgrade/PsBuildTasks/.github/workflows/build-validation-matrix.yml@7970a2024fff722da97a31aa77a20d2b136e4481
