name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Trust PSGallery
        shell: pwsh
        run: Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted

      - name: Install Build Framework
        shell: pwsh
        run: Install-Module InvokeBuild

      - name: Build
        shell: pwsh
        run: Invoke-Build build

      - name: Install Test Dependencies
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          # Invoke-Build requireTestDependencies -Verbose
          Install-Module Pester -Scope CurrentUser -SkipPublisherCheck -Force
          Install-Module PSDocker -Scope CurrentUser -Force
          if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) { exit $LASTEXITCODE }

      - name: Test
        shell: pwsh
        run: Invoke-Pester -Passthru -Verbose

