on:
  push:
    branches: [ develop, bugfix/*, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Trust PSGallery
        shell: pwsh
        run:

      - name: Install build dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop

      - name: Create build
        shell: pwsh
        run: Invoke-Build build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          path: src/PsSqlClient/bin/Debug/netcoreapp2.1/publish
          name: ${{ matrix.os }}-build
  test:
    needs: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          path: src/PsSqlClient/bin/Debug/netcoreapp2.1/publish
          name: ${{ matrix.os }}-build

      - name: Install test dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          # Install-Module Pester -SkipPublisherCheck -Force
          Install-Module PSDocker -ErrorAction Stop

      - name: Run tests
        shell: pwsh
        run: |
          $config = New-PesterConfiguration @{
            'Run.Path' = 'test'
            'Run.Exit' = $true
            'TestResult.Enabled' = $true
            'CodeCoverage.Enabled' = $true
          }
          Invoke-Pester -Configuration $config

      - name: Show workspace
        shell: pwsh
        run: Get-ChildItem -Recurse

