name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Trust PSGallery
        shell: pwsh
        run: Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted

      - name: Install Build Framework
        shell: pwsh
        run: Install-Module InvokeBuild

      - name: Build
        shell: pwsh
        run: Invoke-Build build

      - name: Install Test Dependencies
        shell: pwsh
        run: Invoke-Build requireTestDependencies
        
      - name: Test
        shell: pwsh
        run: Invoke-Pester -Passthru
